import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Box, 
  Music, 
  BookOpen, 
  Compass, 
  Glasses,
  ChevronRight,
  Activity,
  Database,
  Share2,
  Terminal
} from 'lucide-react';

const vectors = [
  {
    id: 'cayley-dickson',
    title: 'The Cayley-Dickson Cosmology Engine',
    icon: Box,
    goal: 'Define the realms and transition mechanics of the game as content-addressed objects.',
    test: 'Can the framework\'s Z/(2^n)Z algebraic structure handle a multi-metric entity moving across a boundary where associativity breaks down (the shift to octonions)? We would look at how the JSON-LD serialization handles the loss of mathematical commutativity/associativity in its properties.',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
  },
  {
    id: 'acoustic-geometry',
    title: 'Acoustic Geometry and the Fano Plane',
    icon: Music,
    goal: 'Map the 7 points and 7 lines of the Fano plane as interacting classes within the ontology, assigning frequency or chordal values to the nodes.',
    test: 'If we query a specific geometric transformation (e.g., rotating the Fano plane), does the UOR framework accurately resolve the resulting cross-products? We would be checking if the data structure can natively calculate the correct "acoustic" output based purely on its geometric relationships.',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
  },
  {
    id: 'epistemological',
    title: 'Epistemological Translation (Vedic Symmetries)',
    icon: BookOpen,
    goal: 'Create a namespace in spec/nemesis/ that encodes the functional roles of the Nityas or the Maruts, defining them not just as cultural concepts, but as specific mathematical operators or forces.',
    test: 'Can the UOR framework cross-reference a Vedic concept with a specific stage of a mathematical trajectory (like the Sage Vortex) without breaking the validation shapes? It’s a test of mapping philosophical mechanics to mathematical mechanics.',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
  },
  {
    id: 'astrogation',
    title: 'Non-Euclidean Astrogation',
    icon: Compass,
    goal: 'Use the UOR-NEMESIS architecture to calculate jump routes. Instead of standard 3D space, the routes require traversing hypercomplex scalar geometries.',
    test: 'We input a starting vector and a destination vector that require moving through a higher-dimensional fold. Can the framework generate the correct sequence of symmetric multi-metric object references to plot the course?',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
  },
  {
    id: 'xr-rendering',
    title: 'Spatial Data Rendering for XR',
    icon: Glasses,
    goal: 'Take a complex dataset generated by the NEMESIS ontology (like a high-dimensional fractal or the Octeract Cypher) and format the JSON-LD output specifically for spatial rendering.',
    test: 'How easily can the mathematical relationships defined in the framework be translated into visual coordinates for a VR environment? We would be testing the bridge between the raw data and the visual interface.',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
  }
];

const CayleyDickson = () => {
  const dimensions = [
    { name: 'Real', symbol: 'R', dim: 1, props: ['Ordered', 'Commutative', 'Associative', 'Alternative'] },
    { name: 'Complex', symbol: 'C', dim: 2, props: ['Commutative', 'Associative', 'Alternative'], lost: 'Ordered' },
    { name: 'Quaternion', symbol: 'H', dim: 4, props: ['Associative', 'Alternative'], lost: 'Commutative' },
    { name: 'Octonion', symbol: 'O', dim: 8, props: ['Alternative'], lost: 'Associative' },
  ];

  return (
    <div className="flex flex-col space-y-4">
      {dimensions.map((d, i) => (
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: i * 0.15 }}
          key={d.name} 
          className="relative flex items-center space-x-4 p-4 bg-blue-900/10 border border-blue-500/20 rounded-lg"
        >
          <div className="flex items-center justify-center w-12 h-12 rounded-full bg-blue-500/20 text-blue-300 font-bold text-xl border border-blue-400/50 shadow-[0_0_15px_rgba(59,130,246,0.2)] z-10">
            {d.symbol}
          </div>
          <div className="flex-1">
            <h4 className="text-blue-100 font-semibold">{d.name} Space (<span className="font-mono text-blue-300">{d.dim}D</span>)</h4>
            <div className="flex flex-wrap gap-2 mt-2">
              {d.props.map(p => (
                <span key={p} className="text-xs px-2 py-1 bg-blue-500/10 text-blue-200 rounded border border-blue-500/20">{p}</span>
              ))}
              {d.lost && (
                <span className="text-xs px-2 py-1 bg-red-500/10 text-red-300 rounded border border-red-500/20 line-through opacity-70">{d.lost}</span>
              )}
            </div>
          </div>
          {i < dimensions.length - 1 && (
            <div className="absolute left-10 top-12 w-0.5 h-8 bg-gradient-to-b from-blue-500/50 to-transparent -z-0" />
          )}
        </motion.div>
      ))}
    </div>
  );
};

const FanoPlane = () => {
  return (
    <svg viewBox="0 0 300 300" className="w-full h-full max-w-sm mx-auto drop-shadow-[0_0_20px_rgba(168,85,247,0.3)]">
      {/* Lines */}
      <line x1="150" y1="50" x2="236.6" y2="200" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      <line x1="236.6" y1="200" x2="63.4" y2="200" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      <line x1="63.4" y1="200" x2="150" y2="50" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      
      {/* Medians */}
      <line x1="150" y1="50" x2="150" y2="200" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      <line x1="236.6" y1="200" x2="106.7" y2="125" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      <line x1="63.4" y1="200" x2="193.3" y2="125" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      
      {/* Inscribed Circle */}
      <circle cx="150" cy="150" r="50" fill="none" stroke="currentColor" strokeWidth="2" className="text-purple-500/40" />
      
      {/* Points */}
      {[
        [150, 50, 'e1'],
        [236.6, 200, 'e2'],
        [63.4, 200, 'e3'],
        [193.3, 125, 'e4'],
        [150, 200, 'e5'],
        [106.7, 125, 'e6'],
        [150, 150, 'e7']
      ].map(([x, y, label], i) => (
        <g key={i}>
          <circle cx={x} cy={y} r="6" className="fill-purple-400" />
          <circle cx={x} cy={y} r="12" className="fill-purple-400/20 animate-pulse" style={{ animationDelay: `${i * 0.2}s` }} />
          <text x={x as number + 12} y={y as number + 4} className="text-[10px] fill-purple-200 font-mono opacity-80">{label}</text>
        </g>
      ))}
    </svg>
  );
};

const Epistemological = () => {
  return (
    <div className="grid grid-cols-[1fr_auto_1fr] gap-6 items-center max-w-lg mx-auto">
      <div className="space-y-6">
        <div className="p-4 bg-amber-900/10 border border-amber-500/20 rounded-xl text-center relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-amber-500/10 to-transparent" />
          <h4 className="text-amber-200 font-serif text-lg relative z-10">Nityas</h4>
          <p className="text-amber-400/60 text-xs mt-1 relative z-10">Eternities / Goddesses</p>
        </div>
        <div className="flex justify-center text-amber-500/30">
          <Activity className="w-5 h-5" />
        </div>
        <div className="p-4 bg-amber-900/10 border border-amber-500/20 rounded-xl text-center relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-amber-500/10 to-transparent" />
          <h4 className="text-amber-200 font-serif text-lg relative z-10">Maruts</h4>
          <p className="text-amber-400/60 text-xs mt-1 relative z-10">Storm Deities</p>
        </div>
      </div>
      
      <div className="relative flex justify-center items-center h-full px-4">
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="w-full h-px bg-gradient-to-r from-amber-500/30 via-white/20 to-cyan-500/30" />
        </div>
        <div className="z-10 bg-[#0a0a0a] p-3 rounded-full border border-white/10 shadow-[0_0_20px_rgba(255,255,255,0.05)]">
          <Share2 className="w-5 h-5 text-white/50" />
        </div>
      </div>

      <div className="space-y-6">
        <div className="p-4 bg-cyan-900/10 border border-cyan-500/20 rounded-xl text-center relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-bl from-cyan-500/10 to-transparent" />
          <h4 className="text-cyan-200 font-mono text-lg relative z-10">Sage Vortex</h4>
          <p className="text-cyan-400/60 text-xs mt-1 relative z-10">Mathematical Trajectory</p>
        </div>
        <div className="flex justify-center text-cyan-500/30">
          <Activity className="w-5 h-5" />
        </div>
        <div className="p-4 bg-cyan-900/10 border border-cyan-500/20 rounded-xl text-center relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-bl from-cyan-500/10 to-transparent" />
          <h4 className="text-cyan-200 font-mono text-lg relative z-10">Cross-Products</h4>
          <p className="text-cyan-400/60 text-xs mt-1 relative z-10">Geometric Resolution</p>
        </div>
      </div>
    </div>
  );
};

const Astrogation = () => {
  return (
    <div className="relative w-full h-72 bg-emerald-950/10 border border-emerald-500/20 rounded-xl overflow-hidden shadow-[inset_0_0_40px_rgba(16,185,129,0.05)]">
      <svg className="absolute inset-0 w-full h-full">
        {/* Grid */}
        <defs>
          <pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse">
            <path d="M 30 0 L 0 0 0 30" fill="none" stroke="rgba(16, 185, 129, 0.05)" strokeWidth="1"/>
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#grid)" />
        
        {/* Euclidean Path (Straight) */}
        <line x1="80" y1="220" x2="480" y2="60" stroke="rgba(16, 185, 129, 0.2)" strokeWidth="1" strokeDasharray="4,4" />
        
        {/* Non-Euclidean Path (Curved/Folded) */}
        <path d="M 80 220 C 150 20, 350 280, 480 60" fill="none" stroke="rgba(16, 185, 129, 0.6)" strokeWidth="2" className="drop-shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
        
        {/* Nodes */}
        <g transform="translate(80, 220)">
          <circle cx="0" cy="0" r="6" className="fill-emerald-400" />
          <circle cx="0" cy="0" r="12" className="fill-emerald-400/20 animate-ping" />
          <text x="-20" y="20" className="text-[10px] fill-emerald-500/70 font-mono">ORIGIN</text>
        </g>
        
        <g transform="translate(480, 60)">
          <circle cx="0" cy="0" r="6" className="fill-emerald-400" />
          <circle cx="0" cy="0" r="12" className="fill-emerald-400/20 animate-ping" style={{ animationDelay: '0.5s' }} />
          <text x="15" y="5" className="text-[10px] fill-emerald-500/70 font-mono">DEST</text>
        </g>
        
        {/* Fold Points */}
        <circle cx="185" cy="100" r="3" className="fill-emerald-300/50" />
        <circle cx="300" cy="150" r="3" className="fill-emerald-300/50" />
        <circle cx="390" cy="180" r="3" className="fill-emerald-300/50" />
      </svg>
      <div className="absolute bottom-4 left-4 p-3 bg-black/40 backdrop-blur-sm border border-emerald-500/20 rounded-lg text-[10px] font-mono text-emerald-400/70 space-y-1">
        <div className="flex items-center space-x-2"><span className="text-emerald-500/50">V_0:</span> <span>[0.2, 0.8, -0.1, 0.5i]</span></div>
        <div className="flex items-center space-x-2"><span className="text-emerald-500/50">V_1:</span> <span>[0.8, 0.2, 0.9, -0.3j]</span></div>
        <div className="flex items-center space-x-2 mt-2 pt-2 border-t border-emerald-500/20"><span className="text-emerald-300">METRIC:</span> <span>NON_EUCLIDEAN_SCALAR</span></div>
      </div>
    </div>
  );
};

const XRRendering = () => {
  return (
    <div className="flex flex-col items-center justify-center h-full space-y-12">
      <div className="relative w-40 h-40 perspective-1000">
        <motion.div 
          animate={{ rotateX: [0, 360], rotateY: [0, 360] }}
          transition={{ duration: 15, repeat: Infinity, ease: "linear" }}
          className="w-full h-full transform-style-3d relative"
        >
          {/* A simple CSS 3D cube representation */}
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'translateZ(80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'translateZ(-80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'rotateY(90deg) translateZ(80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'rotateY(-90deg) translateZ(80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'rotateX(90deg) translateZ(80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
          <div className="absolute inset-0 border border-rose-500/40 bg-rose-500/5 flex items-center justify-center shadow-[0_0_15px_rgba(244,63,113,0.1)]" style={{ transform: 'rotateX(-90deg) translateZ(80px)' }}>
            <div className="w-8 h-8 border border-rose-400/30 rounded-full" />
          </div>
        </motion.div>
      </div>
      <div className="flex items-center space-x-4 text-rose-300 font-mono text-xs bg-rose-950/20 px-5 py-3 rounded-full border border-rose-500/20 shadow-[0_0_20px_rgba(244,63,113,0.05)]">
        <div className="flex items-center space-x-2">
          <Database className="w-4 h-4 text-rose-400/70" />
          <span>JSON-LD</span>
        </div>
        <div className="w-8 h-px bg-gradient-to-r from-rose-500/50 to-transparent" />
        <div className="flex items-center space-x-2">
          <Glasses className="w-4 h-4 text-rose-400/70" />
          <span>XR Viewport</span>
        </div>
      </div>
    </div>
  );
};

export default function App() {
  const [activeId, setActiveId] = useState(vectors[0].id);
  const activeVector = vectors.find(v => v.id === activeId)!;

  return (
    <div className="min-h-screen bg-[#030303] text-slate-300 font-sans selection:bg-indigo-500/30 flex flex-col">
      {/* Header */}
      <header className="border-b border-white/5 bg-black/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 rounded bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center">
              <Terminal className="w-4 h-4 text-indigo-400" />
            </div>
            <h1 className="font-mono text-lg font-semibold tracking-tight text-white">
              NEMESIS<span className="text-white/30">::</span>UOR_FORK
            </h1>
          </div>
          <div className="text-[10px] font-mono text-white/40 flex items-center space-x-2 bg-white/5 px-3 py-1.5 rounded-full border border-white/5">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
            <span>SYSTEM ONLINE</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 md:p-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Sidebar */}
        <div className="lg:col-span-4 space-y-2">
          <h2 className="text-[10px] font-mono text-white/30 uppercase tracking-widest mb-6 px-2">Test Vectors</h2>
          {vectors.map((vector) => {
            const isActive = activeId === vector.id;
            const Icon = vector.icon;
            return (
              <button
                key={vector.id}
                onClick={() => setActiveId(vector.id)}
                className={`w-full text-left flex items-center space-x-4 px-4 py-3.5 rounded-xl transition-all duration-300 border ${
                  isActive 
                    ? `bg-white/5 border-white/10 shadow-lg` 
                    : `border-transparent hover:bg-white/[0.02] hover:border-white/5`
                }`}
              >
                <div className={`p-2.5 rounded-lg transition-colors duration-300 ${isActive ? vector.bgColor : 'bg-white/5'}`}>
                  <Icon className={`w-5 h-5 ${isActive ? vector.color : 'text-white/30'}`} />
                </div>
                <span className={`font-medium text-sm tracking-wide transition-colors duration-300 ${isActive ? 'text-white' : 'text-white/50'}`}>
                  {vector.title}
                </span>
              </button>
            );
          })}
        </div>

        {/* Content Area */}
        <div className="lg:col-span-8">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeId}
              initial={{ opacity: 0, y: 10, filter: 'blur(4px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              exit={{ opacity: 0, y: -10, filter: 'blur(4px)' }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="h-full flex flex-col"
            >
              <div className={`p-1 mb-6 inline-flex rounded-full ${activeVector.bgColor} border ${activeVector.borderColor} self-start`}>
                <div className="px-3 py-1 flex items-center space-x-2">
                  <activeVector.icon className={`w-3.5 h-3.5 ${activeVector.color}`} />
                  <span className={`text-[10px] font-mono font-medium tracking-wider ${activeVector.color}`}>
                    VECTOR_{activeVector.id.replace('-', '_').toUpperCase()}
                  </span>
                </div>
              </div>

              <h2 className="text-3xl md:text-4xl font-bold text-white mb-8 tracking-tight">
                {activeVector.title}
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 hover:bg-white/[0.03] transition-colors">
                  <h3 className="text-[11px] font-mono text-white/40 uppercase tracking-widest mb-4 flex items-center">
                    <ChevronRight className="w-3.5 h-3.5 mr-1.5 text-white/20" /> The Goal
                  </h3>
                  <p className="text-white/70 text-sm leading-relaxed">
                    {activeVector.goal}
                  </p>
                </div>
                <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 hover:bg-white/[0.03] transition-colors">
                  <h3 className="text-[11px] font-mono text-white/40 uppercase tracking-widest mb-4 flex items-center">
                    <ChevronRight className="w-3.5 h-3.5 mr-1.5 text-white/20" /> The Test
                  </h3>
                  <p className="text-white/70 text-sm leading-relaxed">
                    {activeVector.test}
                  </p>
                </div>
              </div>

              <div className="flex-1 bg-[#0a0a0a] border border-white/5 rounded-2xl p-8 relative overflow-hidden min-h-[400px] flex items-center justify-center shadow-2xl">
                {/* Background Grid */}
                <div className="absolute inset-0 opacity-[0.02] pointer-events-none" 
                     style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '32px 32px' }} />
                
                <div className="relative z-10 w-full max-w-2xl">
                  {activeId === 'cayley-dickson' && <CayleyDickson />}
                  {activeId === 'acoustic-geometry' && <FanoPlane />}
                  {activeId === 'epistemological' && <Epistemological />}
                  {activeId === 'astrogation' && <Astrogation />}
                  {activeId === 'xr-rendering' && <XRRendering />}
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
}
